# Generated by Django 5.2.4 on 2025-07-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Affaires", "0003_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evenement",
            name="participants",
        ),
    ]
