# Generated by Django 5.2.4 on 2025-07-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affaires', '0004_remove_evenement_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='tags',
            field=models.CharField(choices=[('agricultur', 'Agriculture'), ('innovation', 'Innovation'), ('partenariats', 'Partanirats'), ('investissement', 'Investissement'), ('financement', 'Financement'), ('autre', 'Autre')], default='default_value', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='categorie',
            field=models.CharField(choices=[('commerciale', 'Commerciale'), ('juridique', 'Juridique'), ('technique', 'Technique'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='titre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='categorie',
            field=models.CharField(choices=[('opportunites', "Opportunités d'affaires"), ('networking', 'Networking'), ('formation', 'Formation'), ('conference', 'Conférence'), ('atelier', 'Atelier')], max_length=50),
        ),
    ]
