# Generated by Django 5.2.4 on 2025-07-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affaires', '0005_evenement_tags_alter_documentation_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='services_proposes',
            field=models.CharField(choices=[('dedouanement', 'Dédouanement'), ('transport', 'Transport'), ('logistique', 'Logistique'), ('conseil_juridique', 'Conseil Juridique'), ('contrats', 'Contrats'), ('financement', 'Financement'), ('autre', 'Autre')], default='logistique', max_length=50),
        ),
    ]
