# Generated by Django 5.2.4 on 2025-07-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affaires', '0006_alter_expert_services_proposes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.CharField(choices=[('opportunites_affaires', "Opportunités d'Affaires"), ('offres_services', 'Offres de Services'), ('recherche_partenaires', 'Recherche de Partenaires'), ('conseil_juridique', 'Conseil Juridique'), ('autre', 'Autre')], default='opportunites_affaires', max_length=50),
        ),
    ]
